# Rule version v1.0.1

- name: "Windows: Application network access account invalid"
  severity: "Medium"
  category: "Potentially Malicious Activity"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.wineventlog.level"
          operator: "in"
          value: "Information,information"
        - field: "logx.wineventlog.event_data.ProviderName"
          operator: "regexp"
          value: "[Mm]icrosoft(.+)[Ww]indows(.+)[Ss]earch"
        - field: "logx.wineventlog.event_id"
          operator: "=="
          value: 3085
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.wineventlog.event_data.SubjectUserName"
          alias: "SourceUser"
        - field: "logx.wineventlog.host.name"
          alias: "SourceHost"
        - field: "logx.wineventlog.event_data.SourceAddress"
          alias: "SourceIP"
        - field: "logx.wineventlog.event_data.SourcePort"
          alias: "SourcePort"
        - field: "logx.wineventlog.event_data.TargetUserName"
          alias: "DestinationUser"
        - field: "logx.wineventlog.event_data.DestAddress"
          alias: "DestinationIP"
        - field: "logx.wineventlog.event_data.DestPort"
          alias: "DestinationPort"
