# Rule version v1.0.1

- name: "Windows: Potential Application Shimming via Sdbinst"
  severity: "Low"
  description: "The Application Shim was created to allow for backward compatibility of software as the operating system codebase
                changes over time. This Windows functionality has been abused by attackers to stealthily gain persistence and arbitrary
                code execution in legitimate Windows processes."
  solution: "Isolate the involved host to prevent further post-compromise behavior.
      Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector.
      If the malicious file was delivered via phishing:
      Block the email sender from sending future emails. Block the malicious web pages.
      Remove emails from the sender from mailboxes. Consider improvements to the security awareness program.
      Run a full antimalware scan. This may reveal additional artifacts left in the system, persistence mechanisms, and malware components."
  category: "Persistence"
  tactic: "Event Triggered Execution"
  reference:
    - "https://attack.mitre.org/tactics/TA0003/"
    - "https://attack.mitre.org/techniques/T1546/"
  frequency: 60
  cache: 
    - allOf:
        - field: "logx.wineventlog.event.type"
          operator: "=="
          value: "start"
        - field: "logx.wineventlog.process.name"
          operator: "contain"
          value: "sdbinst.exe"
        - field: "logx.wineventlog.process.args"
          operator: "not regexp"
          value: "(-m|-bg)"
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.wineventlog.event_data.SubjectUserName"
          alias: "SourceUser"
        - field: "logx.wineventlog.host.name"
          alias: "SourceHost"
        - field: "logx.wineventlog.event_data.SourceAddress"
          alias: "SourceIP"
        - field: "logx.wineventlog.event_data.SourcePort"
          alias: "SourcePort"
        - field: "logx.wineventlog.event_data.TargetUserName"
          alias: "DestinationUser"
        - field: "logx.wineventlog.event_data.DestAddress"
          alias: "DestinationIP"
        - field: "logx.wineventlog.event_data.DestPort"
          alias: "DestinationPort"
