# Rule version v1.0.1

- name: "Privilege Escalation via Windir Environment Variable"
  severity: "High"
  description: "Identifies a privilege escalation attempt via a rogue Windows directory (Windir) environment variable. This is a known
                primitive that is often combined with other vulnerabilities to elevate privileges."
  solution: "Isolate the involved hosts to prevent further post-compromise behavior.
      Review the privileges assigned to the involved users to ensure that the least privilege principle is being followed.
      Determine the initial vector abused by the attacker and take action to prevent reinfection through the same vector."
  category: "Privilege Escalation"
  tactic: "Path Interception by PATH Environment Variable"
  reference:
    - "https://attack.mitre.org/tactics/TA0004/"
    - "https://attack.mitre.org/techniques/T1574/007/"
  frequency: 60
  cache: 
    - allOf:
        - field: "logx.wineventlog.registry.data.strings"
          operator: "not regexp"
          value: "(C:\\\\windows|%SystemRoot%)"
        - field: "logx.wineventlog.registry.path"
          operator: "regexp"
          value: "(HKEY_USERS\\\\(.+)\\\\Environment\\\\windir|HKEY_USERS\\\\(.+)\\\\Environment\\\\systemroot)"
      minCount: 1
      timeLapse: 60
      save:
        - field: "logx.wineventlog.event_data.SubjectUserName"
          alias: "SourceUser"
        - field: "logx.wineventlog.host.name"
          alias: "SourceHost"
        - field: "logx.wineventlog.event_data.SourceAddress"
          alias: "SourceIP"
        - field: "logx.wineventlog.event_data.SourcePort"
          alias: "SourcePort"
        - field: "logx.wineventlog.event_data.TargetUserName"
          alias: "DestinationUser"
        - field: "logx.wineventlog.event_data.DestAddress"
          alias: "DestinationIP"
        - field: "logx.wineventlog.event_data.DestPort"
          alias: "DestinationPort"