- name: "The Windows Firewall Service blocked an application from accepting incoming connections on the network"
  severity: "Low"
  description: "This event generates when an application was blocked from accepting incoming connections on the network by Windows Filtering Platform"
  solution: ""
  category: "Threat Protection"
  tactic: ""
  reference: "https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5031"
  frequency: 60
  cache:
    - allOf:
        - field: "logx.wineventlog.event_id"
          operator: "=="
          value: 5031
      timeLapse: 60
      minCount: 1
      save:
        - field: "logx.wineventlog.host.name"
          alias: "SourceHost"
